foreground #f1dfda
background #1a110f
cursor #ffb59d
cursor_text_color #55200c
selection_foreground #55200c
selection_background #ffb59d
color0 #1a110f

color8 #53433f
color1 #ffb4ab
color9 #ffb4ab
color2 #e7bdb0
color10 #e7bdb0
color3 #d6c68d
color11 #d6c68d
color4 #ffb59d
color12 #ffb59d
color5 #ffb59d
color13 #ffb59d
color6 #e7bdb0
color14 #e7bdb0
color7 #f1dfda
color15 #f1dfda
