foreground #f0dedf
background #1a1112
cursor #ffb2bc
cursor_text_color #561d28
selection_foreground #561d28
selection_background #ffb2bc
color0 #1a1112

color8 #524345
color1 #ffb4ab
color9 #ffb4ab
color2 #e5bdc1
color10 #e5bdc1
color3 #eabf8f
color11 #eabf8f
color4 #ffb2bc
color12 #ffb2bc
color5 #ffb2bc
color13 #ffb2bc
color6 #e5bdc1
color14 #e5bdc1
color7 #f0dedf
color15 #f0dedf
