foreground #e2e2e9
background #111318
cursor #aac7ff
cursor_text_color #0a305f
selection_foreground #0a305f
selection_background #aac7ff
color0 #111318

color8 #44474e
color1 #ffb4ab
color9 #ffb4ab
color2 #bec6dc
color10 #bec6dc
color3 #dcbce0
color11 #dcbce0
color4 #aac7ff
color12 #aac7ff
color5 #aac7ff
color13 #aac7ff
color6 #bec6dc
color14 #bec6dc
color7 #e2e2e9
color15 #e2e2e9
